services:
  minio:
    image: bdp-102/minio:latest
    build:
      context: .
      dockerfile: ./docker/minio.Dockerfile
    hostname: minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .minio.env
    volumes:
      - minio-single-node:/bitnami/minio/data
    networks:
      - custom-network

networks:
  custom-network:
    name: custom-network
    external: true

volumes:
  minio-single-node:
    driver: local