services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=dp-root-user
      - MINIO_ROOT_PASSWORD=dp-root-password
    volumes:
      - minio-single-node:/bitnami/minio/data
    networks:
      - custom-network

networks:
  custom-network:
    name: custom-network
    external: true

volumes:
  minio-single-node:
    driver: local