services: 
  kafka-broker:
    image: bdp-102/kafka-broker
    build:
      context: .
      dockerfile: ./docker/kafka-broker.Dockerfile
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
      - 29093:29093 
    env_file:
      - .broker.env
    networks:
      - custom-network


  kafka-schema-registry:
    image: bdp-102/kafka-registry
    build:
      context: .
      dockerfile: ./docker/kafka-registry.Dockerfile
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka-broker
    ports:
      - 8081:8081
    env_file:
      - .registry.env
    networks:
      - custom-network


  kafka-connect:
    image: bdp-102/kafka-connect
    build:
      context: .
      dockerfile: ./docker/kafka-connect.Dockerfile
    hostname: connect
    container_name: connect
    depends_on:
      - kafka-broker
      - kafka-schema-registry
    ports:
      - 8083:8083
    env_file:
      - .connect.env
    volumes: 
      - ./plugins:/etc/kafka-connect/jars
    networks:
      - custom-network

  rest:
    image: bdp-102/iceberg-rest
    build:
      context: .
      dockerfile: ./docker/iceberg-rest.Dockerfile
    container_name: iceberg-rest
    ports:
      - 8181:8181
    env_file:
      - .iceberg-rest.env
    networks:
      - custom-network

networks:
  custom-network:
    name: custom-network
    external: true

