services:
  postgres:
    image: bdp-102/postgres:latest 
    build:
      context: .
      dockerfile: ./docker/postgres.Dockerfile
    container_name: postgres
    hostname: postgres
    env_file:
      - .postgres.env
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 
    networks:
      - custom-network

networks:
  custom-network:
    name: custom-network
    external: true

