services:
  postgres:
    image: bdp-102/postgres:latest 
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: postgres
    hostname: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - custom-network

networks:
  custom-network:
    name: custom-network
    external: true

